//
// Created by bogdante on 30.07.25.
//

#ifndef TOKENS_H
#define TOKENS_H

typedef enum {
    TK_LITERAL_INT,
    TK_LITERAL_FLOAT,
    TK_LITERAL_CHAR,
    TK_LITERAL_BOOL,
    TK_LITERAL_STRING,

    TK_KEYWORD_U16,
    TK_KEYWORD_U32,
    TK_KEYWORD_U64,
    TK_KEYWORD_I16,
    TK_KEYWORD_I32,
    TK_KEYWORD_I64,
    TK_KEYWORD_F32,
    TK_KEYWORD_F64,
    TK_KEYWORD_U0,
    TK_KEYWORD_BYTE,
    TK_KEYWORD_BOOL,
    TK_KEYWORD_IF,
    TK_KEYWORD_ELSE,
    TK_KEYWORD_WHILE,
    TK_KEYWORD_FOR,
    TK_KEYWORD_RETURN,

    TK_OPERATOR_PLUS,
    TK_OPERATOR_MINUS,
    TK_OPERATOR_MULTIPLY,
    TK_OPERATOR_DIVIDE,
    TK_OPERATOR_ASSIGN,
    TK_OPERATOR_EQUAL,
    TK_OPERATOR_GREATER,
    TK_OPERATOR_GREATER_EQUAL,
    TK_OPERATOR_LESS,
    TK_OPERATOR_LESS_EQUAL,
    TK_OPERATOR_NOT_EQUAL,
    TK_OPERATOR_NOT,
    TK_OPERATOR_AND,
    TK_OPERATOR_OR,
    TK_OPERATOR_AND_AND,
    TK_OPERATOR_OR_OR,

    TK_IDENTIFIER,
    TK_SEMICOLON,
    TK_COMMA,
    TK_LEFT_BRACE,
    TK_RIGHT_BRACE,
    TK_LEFT_PARENTHESES,
    TK_RIGHT_PARENTHESES,
    TK_EOF
}TokenTypes;

#endif //TOKENS_H
